Add collection method to decorate collections of objects
stephendolan/decorator pull request #3
Opened 2021-10-14 17:13 UTC by wout

This PR adds the possibility to use collections as well:

```crystal
UserDecorator.collection([User.new]).first.full_name
```

2021-10-14 17:57 UTC, stephendolan commented
Thanks for this, @wout!

Could you update your PR summary with some examples of how you're planning to use this? I'm having trouble envisioning when you would leverage this outside of an `each` loop when you'd already have access to the individual object you're decorating.

2021-10-14 18:02 UTC, wout commented
For example, when you have an app rendering ERC views and you don't want any logic in them, then it's convenient to have a pre-decorated collection.

2021-10-14 18:05 UTC, stephendolan commented
Cool. Yeah, if you could drop a few code blocks in the PR description for reference to show how you're going to use this, that'd be really helpful!

I often reference or go back to PRs when I'm wondering about pieces of functionality, and I think that context is important for this one.

2021-10-14 18:19 UTC, wout commented
Absolutely, I'll drop some here tomorrow.

2021-10-19 16:29 UTC, wout commented
Sorry, it has taken a bit longer to get back here.

So, I have a fairly generic component in a Lucky app for rendering tables with arbitrary items. Here's a simplified version:

```cr
class Shared::Admin::ItemTable(T) < BaseComponent
  needs items : Array(T)

  def render
    items.any? ? render_table : render_no_items
  end

  private def render_table
    {% begin %}
      {% columns = T.annotation(BaseDecorator::Table)[:columns] %}

      table do
        items.each do |item|
          tr do
            {% for column in columns %}
              td item.{{column.id}}.to_s
            {% end %}
          end
        end
      end
    {% end %}
  end
  # ...
end
```

The type var `T` here is a decorator, and the given decorator is annotated with the necessary attributes for the compiler:

```cr
@[BaseDecorator::Table(columns: %i[email name role])]
struct UserDecorator < BaseDecorator
  decorates user : User

  def name
    "#{first_name} #{last_name}"
  end

  def role
    user.role.name
  end
end
```

Finally, the component is fed with an array of decorators using the `UserDecorator.collection` class method:

```cr
class AdminUsers::IndexPage < AdminLayout
  needs users : UserQuery

  def content
    mount Shared::Admin::ItemTable(UserDecorator),
      items: UserDecorator.collection(users.to_a)
  end
end
```

This is one example, but I can think of more scenarios where the `collection` method may come in handy. You could argue to use the native `map` method everywhere, but that would result in a lot of repetition.

2021-10-21 15:46 UTC, stephendolan commented
Thanks, @wout !

If you can address the few comments I left in the code, this will be good to merge and cut a release 🥳

2021-10-21 16:30 UTC, wout commented
Great, I'd love to. But I don't see any comments. Or am I completely missing something?  :zany_face:

2021-10-21 16:42 UTC, stephendolan requested changes
Oops, I didn't realize I had to submit my review for the comments to show up 😄

2021-10-21 16:42 UTC, stephendolan commented on README.md
> +decorated_times = TimeDecorator.collection([Time.utc])
Can you update your example to show what the output will be with multiple `Time` objects?

2021-10-21 16:42 UTC, stephendolan commented on spec/decorator_spec.cr
> +    UserDecorator.collection([User.new]).first.full_name.should eq "Lucky Casts"
Can you add another test to show that a collection with multiple items also works as expected?

2021-10-21 17:19 UTC, wout commented on README.md
> +decorated_times = TimeDecorator.collection([Time.utc])
Of course, that's done!

2021-10-21 17:20 UTC, wout commented on spec/decorator_spec.cr
> +    UserDecorator.collection([User.new]).first.full_name.should eq "Lucky Casts"
And done as well.

2021-10-21 18:18 UTC, stephendolan approved these changes

2021-10-21 18:18 UTC, merged